# Generated by Django 3.2 on 2021-05-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_author_bought'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelset', models.JSONField(default=[])),
                ('customer_email', models.EmailField(max_length=200)),
                ('stripe_customer_id', models.CharField(max_length=30)),
                ('stripe_customer', models.CharField(max_length=30)),
                ('intent', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
