# Generated by Django 3.2 on 2021-05-06 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210506_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 12, 45, 32, 771364, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
