# Generated by Django 3.2 on 2021-05-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentsession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
