# Generated by Django 3.2 on 2021-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_debt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
