# Generated by Django 3.2 on 2021-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210510_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('account_id', models.CharField(max_length=30)),
                ('modelset', models.JSONField(default=[])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
