# Generated by Django 3.2 on 2021-05-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210511_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
