# Generated by Django 3.2 on 2021-05-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_mod_model_author_price'),
        ('payment', '0009_delete_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('account_id', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.mod')),
            ],
        ),
    ]
