# Generated by Django 4.0 on 2022-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsession',
            name='modelset',
            field=models.JSONField(default=list),
        ),
    ]
