# Generated by Django 2.2.19 on 2021-04-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mod',
        ),
    ]
