# Generated by Django 2.2.19 on 2021-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_file',
            field=models.FileField(upload_to='storage/'),
        ),
    ]
