# Generated by Django 2.2.19 on 2021-04-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210408_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mod',
        ),
    ]
