# Generated by Django 2.2.19 on 2021-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210408_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_file',
            field=models.FileField(upload_to='storage/model'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='model_image',
            field=models.ImageField(upload_to='storage/image'),
        ),
    ]
