# Generated by Django 3.2 on 2021-04-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210408_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mod',
        ),
    ]
