# Generated by Django 3.2 on 2021-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=None, upload_to='static/storage/img/categories'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='model_file',
            field=models.FileField(upload_to='static/storage/models'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='model_image',
            field=models.ImageField(upload_to='static/storage/img/models'),
        ),
    ]
