# Generated by Django 3.2 on 2021-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210411_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='Empty', upload_to='static/storage/img/categories'),
        ),
    ]
