# Generated by Django 3.2 on 2021-04-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
