# Generated by Django 3.2 on 2021-04-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_mod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
