# Generated by Django 3.2 on 2021-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_category_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='None', upload_to='static/storage/img/categories'),
            preserve_default=False,
        ),
    ]
