# Generated by Django 3.2 on 2021-04-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='model_prise',
            new_name='model_price',
        ),
    ]
