# Generated by Django 3.2 on 2021-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_specialuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='favs',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
