# Generated by Django 3.2 on 2021-04-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0024_auto_20210414_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
