# Generated by Django 3.2 on 2021-04-17 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Author',
        ),
    ]
