# Generated by Django 3.2 on 2021-04-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_profile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foll',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='subs',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
