# Generated by Django 3.2 on 2021-04-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0028_auto_20210418_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
