# Generated by Django 3.2 on 2021-04-18 11:12

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0029_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(upload_to='static/storage/img/user')),
                ('cart', models.JSONField()),
                ('favs', models.JSONField()),
                ('subs', models.JSONField()),
                ('foll', models.JSONField()),
                ('bday', models.DateTimeField()),
                ('bio', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('favtool', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
