# Generated by Django 3.2 on 2021-04-20 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210420_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bday',
            field=models.DateTimeField(default=datetime.date(2021, 4, 20)),
        ),
        migrations.AlterField(
            model_name='author',
            name='cart',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='author',
            name='favs',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='author',
            name='foll',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='author',
            name='subs',
            field=models.JSONField(default=[]),
        ),
    ]
