# Generated by Django 3.2 on 2021-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210420_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(default='Bio', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='location',
            field=models.CharField(default='Moon, Utopia', max_length=100),
        ),
    ]
