# Generated by Django 3.2 on 2021-04-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_category_sing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sing',
            new_name='sign',
        ),
    ]
