# Generated by Django 3.2 on 2021-04-22 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210420_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bday',
            field=models.DateTimeField(default=datetime.date(2021, 4, 22)),
        ),
        migrations.AlterField(
            model_name='author',
            name='cart',
            field=models.JSONField(default=set()),
        ),
        migrations.AlterField(
            model_name='author',
            name='favs',
            field=models.JSONField(default=set()),
        ),
        migrations.AlterField(
            model_name='author',
            name='foll',
            field=models.JSONField(default=set()),
        ),
        migrations.AlterField(
            model_name='author',
            name='subs',
            field=models.JSONField(default=set()),
        ),
    ]
