# Generated by Django 3.2 on 2021-04-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210422_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cart',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='author',
            name='favs',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='author',
            name='foll',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='author',
            name='subs',
            field=models.JSONField(default=[]),
        ),
    ]
