# Generated by Django 3.2 on 2021-04-30 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_mod_model_favs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bday',
            field=models.DateTimeField(default=datetime.date(2021, 4, 30)),
        ),
        migrations.AlterField(
            model_name='mod',
            name='model_price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='model_views',
            field=models.FloatField(default=0),
        ),
    ]
