# Generated by Django 3.2 on 2021-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210430_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_price',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mod',
            name='model_views',
            field=models.IntegerField(default=0),
        ),
    ]
