# Generated by Django 3.2 on 2021-04-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210430_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='model_downloads',
        ),
    ]
