# Generated by Django 3.2 on 2021-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210501_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='payments',
            field=models.JSONField(default=[]),
        ),
    ]
