# Generated by Django 3.2 on 2021-05-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_author_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
