# Generated by Django 3.2 on 2021-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_author_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='vipstatus',
            field=models.BooleanField(default=False),
        ),
    ]
