# Generated by Django 3.2 on 2021-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_author_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='credit',
            field=models.CharField(default='Empty', max_length=20),
        ),
    ]
