# Generated by Django 3.2 on 2021-05-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0050_alter_author_bday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='model_author',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='model_category',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Mod',
        ),
    ]
