# Generated by Django 3.2 on 2021-05-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('amount', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='static/storage/img/categories')),
                ('sign', models.CharField(default='exclamation', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
                ('model_desc', models.TextField()),
                ('model_price', models.FloatField(max_length=20)),
                ('model_date', models.DateTimeField()),
                ('model_image', models.ImageField(upload_to='static/storage/img/models')),
                ('model_file', models.FileField(upload_to='static/storage/models')),
                ('model_views', models.IntegerField(default=0)),
                ('model_tags', models.JSONField()),
                ('model_tool', models.CharField(max_length=50)),
                ('model_favs', models.IntegerField(default=0)),
                ('model_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('model_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.category')),
            ],
        ),
    ]
