# Generated by Django 3.2 on 2021-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_price',
            field=models.IntegerField(max_length=20),
        ),
    ]
