# Generated by Django 3.2 on 2021-05-04 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_mod_model_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 9, 50, 3, 937065, tzinfo=utc)),
        ),
    ]
