# Generated by Django 3.2 on 2021-05-04 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_alter_mod_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 10, 52, 38, 612178, tzinfo=utc)),
        ),
    ]
