# Generated by Django 3.2 on 2021-05-05 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_alter_mod_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 10, 50, 56, 164040, tzinfo=utc)),
        ),
    ]
