# Generated by Django 3.2 on 2021-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_auto_20210506_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_price',
            field=models.FloatField(),
        ),
    ]
