# Generated by Django 3.2 on 2021-05-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_alter_mod_model_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='model_name',
            field=models.CharField(max_length=30),
        ),
    ]
