# Generated by Django 3.2 on 2021-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_alter_mod_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='model_author_price',
            field=models.FloatField(default=0),
        ),
    ]
