# Generated by Django 3.2 on 2021-05-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_mod_model_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='model_image',
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='static/storage/img/models')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.mod')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/storage/models')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.mod')),
            ],
        ),
    ]
