# Generated by Django 4.0 on 2022-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='E:\\Server\\Projects\\aviators/static/storage/img/categories'),
        ),
    ]
