# Generated by Django 3.2 on 2021-05-04 09:27

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(upload_to='static/storage/img/user')),
                ('cart', models.JSONField(default=[])),
                ('favs', models.JSONField(default=[])),
                ('subs', models.JSONField(default=[])),
                ('foll', models.JSONField(default=[])),
                ('bday', models.DateTimeField(default=datetime.datetime(2021, 5, 4, 9, 27, 49, 386483, tzinfo=utc))),
                ('bio', models.CharField(default='Bio', max_length=255)),
                ('website', models.URLField()),
                ('location', models.CharField(default='Moon, Utopia', max_length=100)),
                ('favtool', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(default='None', max_length=10)),
                ('credit', models.CharField(default='Empty', max_length=20)),
                ('notifications', models.JSONField(default=[])),
                ('payments', models.JSONField(default=[])),
                ('coins', models.IntegerField(default=0)),
                ('vipstatus', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
