# Generated by Django 3.2 on 2021-05-04 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_author_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bday',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 9, 50, 3, 934481, tzinfo=utc)),
        ),
    ]
