# Generated by Django 3.2 on 2021-05-04 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_author_bday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favs',
        ),
        migrations.RemoveField(
            model_name='author',
            name='subs',
        ),
        migrations.AlterField(
            model_name='author',
            name='bday',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 10, 49, 50, 63148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='author',
            name='coins',
            field=models.JSONField(default=[]),
        ),
    ]
