# Generated by Django 3.2 on 2021-05-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210504_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bday',
        ),
    ]
