# Generated by Django 3.2 on 2021-05-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_author_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=10)),
                ('holder_name', models.CharField(max_length=100)),
                ('holder_type', models.CharField(max_length=20)),
                ('routing_number', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('stripe_bank_id', models.CharField(max_length=30)),
                ('fingerprint', models.CharField(max_length=30)),
                ('last4', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.author')),
            ],
        ),
    ]
