# Generated by Django 3.2 on 2021-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bank_account',
            field=models.IntegerField(default=-1, max_length=10),
        ),
        migrations.AlterField(
            model_name='author',
            name='credit',
            field=models.CharField(max_length=20),
        ),
    ]
