# Generated by Django 3.2 on 2021-05-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210510_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='paypal_account',
            field=models.IntegerField(default=-1, max_length=10),
        ),
    ]
