# Generated by Django 3.2 on 2021-05-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_submited_stripeaccount_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeaccount',
            name='business_link',
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='currency',
        ),
        migrations.AddField(
            model_name='stripeaccount',
            name='business_profile',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
