# Generated by Django 3.2 on 2021-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210510_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paypal_account',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='author',
            name='stripe_account',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='transfers',
            field=models.CharField(max_length=10),
        ),
    ]
