# Generated by Django 3.2 on 2021-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210511_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
