# Generated by Django 4.0 on 2022-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_author_warnings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeAccount',
        ),
        migrations.AlterField(
            model_name='author',
            name='bought',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='cart',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='coins',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='favs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='notifications',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='payments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='author',
            name='reports',
            field=models.JSONField(default=list),
        ),
    ]
